name: event_bloc
description: Event Bloc is an event-based implementation of the BLoC pattern, the recommended State Management Pattern for Flutter by Google!
version: 4.3.3
repository: https://github.com/VHCBlade/event_bloc

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.0.0
  provider: ^6.0.0
  meta: ^1.0.0

  equatable: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  event_bloc_tester: ^0.1.1
  tuple: ^2.0.0

flutter:
