name: event_bloc
description: Event Bloc is an event-based implementation of the BLoC pattern, the recommended State Management Pattern for Flutter by Google!
version: 4.4.0
repository: https://github.com/VHCBlade/event_bloc

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  collection: ^1.0.0
  equatable: ^2.0.0
  
  flutter:
    sdk: flutter

  meta: ^1.0.0
  provider: ^6.0.0


dev_dependencies:
  event_bloc_tester: ^0.1.4
  flutter_test:
    sdk: flutter

  tuple: ^2.0.0
  very_good_analysis: ^4.0.0

flutter:
